## 테스트 함수들
### test
```js
test(테스트명, 테스트 함수)
```
첫번째 인자에는 테스트 내용을 잘 나타내는 제목을 할당합니다.
두번째 인자에는 테스트 기댓값과 검증값이 일치하는 단언문을 작성합니다.
### expect
expect의 인자에는 검증값이 들어갑니다.
단언문: `expect(검증값).toBe(기댓값)`
### toBe
toBE의 인자로는 기댓값이 들어갑니다.
매처: `toBe(기댓값)`

```
// ex
test("1 + 1은 2", () => {
	expect(1 + 1).toBe(2)
})
```
### describe
describe함수는 test 함수와 다르게 중첩이 가능합니다.
따라서 테스트를 그룹화 할 수 있습니다.
```
describe("사칙연산" () => {
  describe("덧셈", () => {
	test("1 + 1은 2", () => {
	  expect(1+1).toBe(2)
	})
	test("2 + 2는 4", () => {
	  expect(2+2).toBe(4)
	})
	})
  describe("뺼셈", () => {
	test("2 - 1는 1", () => {
	  expect(2-1).toBe(1)
	})
	test("3 - 2는 1", () => {
	  expect(3-2).toBe(1)
	})
  })
})
```

## 테스트 실행하기
프로젝트의 package.json에 test script를 추가해줍니다.
```
//package.json
{
	scripts: {
		"test": "jest"
	}
}
```
npm test 명령어를 수행하면 해당 프로젝트의 전체 테스트 코드를 수행하게 됩니다.
### 부분 테스트 & jest runner(vsc extension)
만약 1000개의 테스트 코드가 있다고 가정해보겠습니다.
하나의 테스트 코드를 추가하고 추가한 테스트 코드를 테스트하기 위해
위에서 추가한 `npm script`를 수행한다면 테스트가 완료되기까지 1000번의 테스트를 모두 기다려야할 것입니다.
그래서 이런 번거로운 과정들을 수행하지 않고 vscode의 **jest runner**라는 extension을 사용하면 **부분적으로 테스트**가 가능합니다.

[jest runner 참고](https://marketplace.visualstudio.com/items?itemName=firsttris.VSCode-jest-runner)

## 예외 발생 시키기
```js
test("인수가 '0~100'의 범위밖이면 예외가 발생한다", () => {
	expect(add(-20, 100)).toThrow(Error)
})
```
다음과 같은 상황에서 add의 인자에 0~100 범위 밖의 인수가 들어오는 경우 에러가 발생하도록 함수를 설정할 것이다.
```ts
class RangeError extends Error {}

function checkRange(value: number) {
	if (value < 0 || value > 100) {
		throw new RangeError("0〜100 사이의 값을 입력해주세요");
	}
}

export function add(a: number, b: number) {
	checkRange(a);
	checkRange(b);
	const sum = a + b;
	if (sum > 100) {
		return 100;
	}
	return sum;
}
```
위 코드와 같이 연산을 수행하기전 인자의 값을 검증하여 범위 밖의 인수가 들어오는 경우 에러를 발생시킵니다.
이때 Error 클래스를 상속 받아 만든 RangeError 클래스에 의해 에러를 발생시킵니다.

```ts
test("인수가 '0~100'의 범위밖이면 예외가 발생한다", () => {
	cosnt message = "0〜100 사이의 값을 입력해주세요"
	expect(add(-20, 120)).toThrow(RangeError)
	expect(add(-10, 100)).toThrow(RangeError)
	expect(add(0, 120)).toThrow(Error)
	expect(add(-30, -40)).toThrow(message)
})
```
다음과 같이 에러를 발생시키는 코드에 대해서는 위와 같이 테스트 코드를 작성할 수 있습니다.
expect에 예외가 발생하는 함수를 할당하고, 매처로는 `toThrow`를 사용합니다.

toThrow에는 에러메세지, 클래스를 할당하여 발생한 에외에 대해서 검증할 수 있습니다.
단, 위의 예시처럼 `RangeError`의 부모 클래스인 `Error`도 할당이 가능하지만 부모를 할당하는 것보다는 세분화한 클래스를 할당하는 것이 적절합니다.

## 용도별 매처
매처는 용도와 상황에 따라 적절한 매처를 사용해야합니다. 다양한 매처에 대해 알아봅시다.

### 진리값 검증
####  toBeTruthy
참인 값과 일치하는 매처
#### toBeFalsy
거짓인 값과 일치하는 매처
#### toBeNull & toBeUndefined
null과 undefined 모두 `toBeFalsy`와도 일치하지만 더 나아가 null과 undefined를 검증하고 싶을 때에는 `toBeNull`과 `toBeUndefined`를 사용하는 것이 좋다.

위 함수들에 .not을 붙이면 부정이 가능하다
### 문자열 검증
#### toContain
특정 문자열 포함여부
배열에 **원시형**인 특정 값이 확인할 때도 사용
#### toMatch
정규식 검증 매처
#### toHaveLength
문자열 & 배열 길이 검증 매처
#### stringContaining & stringMatching
객체에 포함된 문자열 검증
### 배열 검증
#### toContainEqual
배열에 특정 객체가 포함되어 있는지 검증
#### arrayContaining
인수로 넘겨준 배열의 요소들이 모두 포함되어 있는지 검증
```ts
describe("객체들로 구성된 배열", () => {
	const article1 = { author: "taro", title: "Testing Next.js" };
	const article2 = { author: "jiro", title: "Storybook play function" };
	const article3 = { author: "hanako", title: "Visual Regression Testing" };
	const articles = [article1, article2, article3];

	test("toContainEqual", () => {
		expect(articles).toContainEqual(article1);
	});
	test("arrayContaining", () => {
		expect(articles).toEqual(expect.arrayContaining([article1, article3]));
	});
});
```
### 객체 검증
#### toMatchObject
부분적으로 프로퍼티가 일치하는지 검증
####  toHaveProperty
객체에 특정 프로퍼티가 있는지 검증
#### objectContaining

```ts
describe("객체 검증", () => {
	const author = { name: "taroyamada", age: 38 };
	const article = {
		title: "Testing with Jest",
		author,
	};

	test("toMatchObject", () => {
		expect(author).toMatchObject({ name: "taroyamada", age: 38 });
		expect(author).toMatchObject({ name: "taroyamada" });
		expect(author).not.toMatchObject({ gender: "man" });
	});
	
	test("toHaveProperty", () => {
		expect(author).toHaveProperty("name");
		expect(author).toHaveProperty("age");
	});
	
	test("objectContaining", () => {
		expect(article).toEqual({
			title: "Testing with Jest",
			author: expect.objectContaining({ name: "taroyamada" }),
		});
	
		expect(article).toEqual({
			title: "Testing with Jest",
			author: expect.not.objectContaining({ gender: "man" }),
		});
	});
});
```
## 비동기 처리 테스트
```ts
function wait(duration: number) {
	return new Promise((resolve) => {
		setTimeout(() => {
			resolve(duration)
		}, duration);
	});
}
```
위 함수를 테스트 한다고 가정해보겠습니다.
인자에 시간을 넣었을 때 넣은 시간 이후에 넣은 시간을 반환하는 함수입니다.
### Promise를 반환하는 작성법
#### then을 이용한 방법
```ts
test('지정 시간을 기다린 뒤 경과 시간과 함께 resolve된다', () => {
	return wait(50).then((duration) => {
		expect(duration).toBe(50);
	});
});
```
then을 이용하여 Prmise가 반환하는 값을 처리 완료까지 기다렸다가 테스트를 수행한다.
#### resolves 매처를 이용한 방법
```ts
test('지정 시간을 기다린 뒤 경과 시간과 함께 resolve된다', () => {
	return expect(wait(50)).resolves.toBe(50);
});
```
resolve 함수를 이용하면 함수가 resolve됐을 때 값을 검증한다.(then을 썼을 때보다 더 간결해짐)
### async/await를 이용한 방법
#### 테스트 함수를 async 함수로 만들고 Promise가 완료될 때까지 기다리는 방법
resolves 매처를 사용하는 단언문도 `await`로 대기시킬 수 있다.
```ts
test('지정 시간을 기다린 뒤 경과 시간과 함께 resolve된다', async () => {
	await expect(wait(50)).resolves.toBe(50);
});
```

#### 검증값인 Promise가 완료되는 것을 기다린 뒤 단언문을 실행하는 방법
```ts
test('지정 시간을 기다린 뒤 경과 시간과 함께 resolve된다', async () => {
	expect(await wait(50)).toBe(50);
});
```
가장 간략한 방법

## Reject 검증 테스트
```ts
export function timeout(duration: number) {
	return new Promise((_, reject) => {
		setTimeout(() => {
			reject(duration);
		}, duration);
	});
}
```
위와 같은 reject되는 코드의 함수를 이용해 reject를 검증해보자
#### catch 메서드를 사용한 방법
```ts
test('지정 시간을 기다린 뒤 경과 시간과 함께 reject된다', () => {
	return timeout(50).catch((duration) => {
		expect(duration).toBe(50);
	});
});
```
#### reject 매처를 사용하는 단언문을 활용한 방법
```ts
test('지정 시간을 기다린 뒤 경과 시간과 함께 reject된다', () => {
	return expect(timeout(50)).rejects.toBe(50);
});
```
return을 이용
```ts
test('지정 시간을 기다린 뒤 경과 시간과 함께 reject된다', async () => {
	await expect(timeout(50)).rejects.toBe(50);
});
```
aysnc/await 이용
#### try-catch 문을 사용한 방법
```ts
test('지정 시간을 기다린 뒤 경과 시간과 함께 reject된다', async () => {
	expect.assertions(1);
	try {
		await timeout(50);
	} catch (err) {
		expect(err).toBe(50);
	}
});
```
이때 `assertions`는 수행 횟수를 말한다.
`assertion`를 추가하면 비동기 처리 테스트를 할 때 사소한 실수를 줄일 수 있다.



```ts
test('return하고 있지 않으므로 Promise가 완료되기 전에 테스트가 종료된다', () => {
	// 실패할 것을 기대하고 작성한 단언문
	// expect(wait(2000)).resolves.toBe(3000);
	// 올바르게 고치려5면 다음 주석처럼 단언문을 return해야 한다
	return expect(wait(2000)).resolves.toBe(3000);
});
```
비동기 테스트를 할 때 테스트 함수가 동기인 경우 단언문을 반드시 `return`해야 한다. 그렇지 않으면 위 코드의 주석 처럼 실패를 기대하고 작성한 단언문이 성공으로 판단될 수도 있다.